# To build this android project you must have
# the arduino sdk (1.0.x) installed, see the arduino.mk
# file for more details, on that.
#
# Then you must get the USB_Host_Shield_2.0 from github:
# https://github.com/felis/USB_Host_Shield_2.0
# and put it in the <arduino_sdk>/libraries/USB_Host_Shield
#
# Then just issue make.

SOURCES   = scopeduino.cpp
TARGET    = scopeduino
LIBRARIES = USB_Host_Shield
BOARD     = mega2560
include arduino.mk
